// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoCSQl4OPc84hXn7rm_7E3nIh-5STFDvM',
    appId: '1:343383431472:web:9b6e3fde2264c9b7c010f5',
    messagingSenderId: '343383431472',
    projectId: 'fir-demo-1d49f',
    authDomain: 'fir-demo-1d49f.firebaseapp.com',
    storageBucket: 'fir-demo-1d49f.firebasestorage.app',
    measurementId: 'G-67GMVN9NSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx_cAXClTyKGv-OWoIrKripqpcx5el02Y',
    appId: '1:343383431472:android:9af3861bf2d6f589c010f5',
    messagingSenderId: '343383431472',
    projectId: 'fir-demo-1d49f',
    storageBucket: 'fir-demo-1d49f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Ifun_bj34Bcxo7MHzVld2Kzn8PydFwQ',
    appId: '1:343383431472:ios:843cf2572a9e2565c010f5',
    messagingSenderId: '343383431472',
    projectId: 'fir-demo-1d49f',
    storageBucket: 'fir-demo-1d49f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Ifun_bj34Bcxo7MHzVld2Kzn8PydFwQ',
    appId: '1:343383431472:ios:843cf2572a9e2565c010f5',
    messagingSenderId: '343383431472',
    projectId: 'fir-demo-1d49f',
    storageBucket: 'fir-demo-1d49f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoCSQl4OPc84hXn7rm_7E3nIh-5STFDvM',
    appId: '1:343383431472:web:015f2316653b6a00c010f5',
    messagingSenderId: '343383431472',
    projectId: 'fir-demo-1d49f',
    authDomain: 'fir-demo-1d49f.firebaseapp.com',
    storageBucket: 'fir-demo-1d49f.firebasestorage.app',
    measurementId: 'G-TWNJV7NCGP',
  );
}
